[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; --- Configuración específica para N16R8 (16MB Flash / 8MB PSRAM Octal) ---
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv

build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    ; Activa el puerto USB nativo para grabación y consola serial (OTG)
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MSC_ON_BOOT=0
    -DARDUINO_USB_DFU_ON_BOOT=0

board_build.arduino.memory_type = qio_opi

lib_deps =
    tzapu/WiFiManager @ ^2.0.17
    bblanchon/ArduinoJson @ ^7.0.4